site_name: chatbox-modelscope-sync-mcp PyPi package
site_description: Documentation for the project
repo_url: https://github.com/ztxtech/chatbox-modelscope-sync-mcp
repo_name: ztxtech/chatbox-modelscope-sync-mcp
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
nav:
- Home: index.md
- API Reference:
  - Api Overview: api/index.md
  - Cli: api/cli.md
  - Sync: api/sync.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true
          show_source: true
